### ISSUE TITLE
Beta 1 & 2

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#48]
What happened to beta 1 and beta 2? I think everyone involved in Compose has asked about this, and it's actually bothering me now.

The reason versions are tagged with beta3 is to have some form of indication that we run against the associated beta3 versions of the microsoft dependencies.

However, I think the nuspec's can convey that without tainting our semver.

Any objections @mattridgway / @herecydev ?

**Comment by herecydev** [comment]
Your versions should be relevant to your project. Nuget resolves the dependencies for you, so there's no need to "care" about what versions the package relies on.

**Comment by mattridgway** [comment]
I would agree with @herecydev

**Comment by sblackler** [comment]
Agreed with @herecydev

**Comment by herecydev** [comment]
Good good ... Let the fanboys flow through me!

**Comment by Smudge202** [comment]
Nah, @herecydev is wrong.  I'm releasing beta 27.
