### ISSUE TITLE
CoreCLR compatibility

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#53]

**Comment by herecydev** [comment]
Any update on this? Reinstalling VS so not sure if its building but looks good!

**Comment by smudge202** [comment]
Don't think it was building when I last played with this branch. I hope to finish the work this week.

**Comment by smudge202** [comment]
Just as an update on this, the hold back is no long Compose. Fluent Assertions is not dnx-ready. I took control of porting FluentAssertions but that is blocked by aspnet/dnx#1883.

I doubt anyone will get round to looking at that dnx issue for a while, so I've started a new simple Fluent library that Compose can use in the interim.

Once the new Fluent library has sufficient support for Compose's usage, I'll push the CoreCLR branch of Compose and publish the Fluent library to NuGet.

**Comment by smudge202** [comment]
Resolved by #73
