### ISSUE TITLE
Context only executable

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#57]
Due to the current Executable structure, it is not possible to define a `TContext` without a `TResult`.

**Comment by smudge202** [comment]
Moving this back to v0.1.5-beta because it does not block ongoing development of consumer software.

**Comment by smudge202** [comment]
There is no *good* way of doing this.

Essentially, `Executable` currently works in the same way as `System.Task`. When not generic, it is basically `Func<void>`, otherwise it is `Func<T>`. You can provide a context using `Executable<TContext, TResult>` which is no different to `Task< T, TResult>` and `Func<T, TResult>`.

The issue is that there is no way to supply a context and return a void, in the same way you can't use `Func<T, void>`. Instead, you would use `Action<T>`.

Probably the most difficult issue here is with regards to naming. `Executable` correctly reflects the behaviour extended by the class. The obvious choice would be to have `Executable` which is assumed to have no return (`Action` based), and `ReturnableExecutable` or similar for returns (`Func` based).

However, the default behaviour of most applications is to return something, so I want the API to have the `Func` based as a first class citizen, and `Action` based as second class if necessary. `ReturnableExecutable` does the opposite in my opinion.

Here are a couple (still ugly) ideas, be interested in your thoughts @sblackler / @herecydev .

### Option 1 - *Second Class Context Only*

```c#
public class Executable 
{
  void Execute();
}

public class Executable<T>
{
  T Execute();

  public class ContextOnly
  {
    void Execute(T context);
  }
}

public class Executable<TContext, TResult>
{
  TResult Execute(TContext context);
}

// usage
public class MyApplication : Executable<MyContext>.ContextOnly { }
```

This has the advantage of not changing the API too much, and introducing `ContextOnly` as a second class citizen.

### Option 2 - *Second Class Everything*

```c#
public class Executable
{
  void Execute();

  public class WithContext<TContext>
  {
    void Execute(TContext context);

    public class Returning<TResult>
    {
      TResult Execute(TContext context);
    }
  }
  public class Returning<TResult>
  {
    TResult Execute();
  }
}
```

This has the advantage of not favouring `Action` / `Func` based types, but does make everything slightly more verbose.

**Comment by smudge202** [comment]
Obviously, I'm all in favour of Option 3 if people have a better idea?

**Comment by sblackler** [comment]
Option 2 seems to be the most appropriate. The verbosity is minimal, but it clearly states what you hope to achieve.

**Comment by herecydev** [comment]
I dislike option 2; almost always I'm returning (I think that's the best practice) so please don't shittify the existing API!

**Comment by smudge202** [comment]
I'm in agreement with @herecydev . We currently only have one case where we need Context Only (though workaround it by returning the context). Not to say there won't be more, but Returning is definitely the most common by far.

**Comment by smudge202** [comment]
Check out 2d58167ddc1a93ba41585e969ee0e10dc36d1e50 , think that covers this issue?

**Comment by herecydev** [comment]
Seems good to me, I would consider keeping the `TResult` and adding the `TContext` to make it explicit about the behavior. Other than that it's kind of the solution we talked about.
