### ISSUE TITLE
Application.GetRequiredService exception

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#60]
When the service is not present in the `IServiceCollection`, `Microsoft.Framework.DependencyInjection` raises the following exception:
```
Object cannot be null.
Parameter name: source
```
This needs to be a typed exception from Compose explaining the service was not registered.

**Comment by smudge202** [comment]
//cc @herecydev (in case you fancy some more)

**Comment by herecydev** [comment]
I'm happy to help always. Will be afk for a few days but if you can wait I will do this on return.

**Comment by smudge202** [comment]
No rush, was more for if you were bored today. Not urgent, I may do it over weekend so check back before starting on it. ;)

**Comment by herecydev** [comment]
Don't worry about it. Use your skills on the coreclr :)

**Comment by herecydev** [comment]
Right, had a crack at it and came up with the following issue. During your `Application.GetRequiredService()` you are trying to get the service and if that doesn't work then trying to resolveselfbound. I assumed you meant something like `app.GetRequiredService<myclass>()` and for that to automatically bind itself and return an instance.

I came up with the following:

``` c#
protected internal T GetRequiredService<T>() where T : class
{
	var service = Provider.GetService<T>();
		if (service != null)
		return service;
	var serviceType = typeof(T);
        if (!serviceType.IsInterface)
		return ResolveSelfBound<T>();
	throw new ServiceNotRegisteredException($"Service of type {serviceType.AssemblyQualifiedName} was not registered");
}
```

But that doesn't play well with your transitional stuff. I don't fully comprehend what you're doing with all of this so hopefully you can explain that part better
