### ISSUE TITLE
Investigate compatibility with IDisposable

### ISSUE THREAD

**Issue by sblackler** [smudge202/compose#66]
We need to ensure that dispose is called deterministically for components when they are no longer required. The main situations that come to mind are: 

- When the host is killed
- During any transition
- Snapshotting

As @smudge202 noted, handling the disposal during transitioning becomes quite complex as if the object is in transient scope then we should defer to the scope of the consumer. This is also further complicated by the snapshotting mechanism of compose.

**Comment by smudge202** [comment]
Transitioning processes do not honour the original scope of a service registration. IIRC, all transitions are singleton.

It may not be possible to honour this when transitioning; though possibly if the dynamic proxies are injected with factories and only maintain weak references.

Is there a business requirement for this, @sblackler ?

**Comment by mattridgway** [comment]
@sblackler if you transitioned to another service, then snapshotted back - would you expect to get the same instance back?

**Comment by smudge202** [comment]
^ Yes, though complications arise as per #67

**Comment by smudge202** [comment]
This issue has been broken out into #67, #68, #69
