### ISSUE TITLE
README Trolling

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#71]
We only need the README's to display after installation, not be included in the project.

@herecydev particularly enjoys this bug.

**Comment by herecydev** [comment]
You like things to be included into projects don't you! #wheresyourtestattributespr

**Comment by smudge202** [comment]
Under the `project.json` system I don't know how to include the `readme` in the `nupkg` without it being installed, so CoreCLR branch may mean we kill off the `readme` for a while until I work out how to do that.

**Comment by smudge202** [comment]
I've created #76 to review this in the future.

This has been resolved as part of the structural change found here:  4Com/compose#1
