### ISSUE TITLE
AppendSingleton -> AddSingleton

### ISSUE THREAD

**Issue by herecydev** [smudge202/compose#75]
As seen [here](https://github.com/smudge202/compose/blob/dev/src/Compose/ISingletonRepositoryServiceProvider.cs#L7).
Appending suggests order is important. Would it therefore be better to rename this to AddSingleton?

**Comment by smudge202** [comment]
Order is important. If you use `services.AddSingleton` during composition then it makes no difference. However, `AppendSingleton`'s can happen post-composition and there is an implicit cost in doing so (such as recycling the root provider).

**Comment by herecydev** [comment]
Ah okay, I could only find 1 implementation

**Comment by smudge202** [comment]
I think there will be a considerable shake up of how this stuff works as part of several upcoming changes regarding the rot provider, singleton management, and proxy registration. Let's keep this open as a reminder for when that work is complete.

**Comment by smudge202** [comment]
This has been resolved as part of the structural change found here:  4Com/compose#1
