### ISSUE TITLE
Application review

### ISSUE THREAD

**Issue by herecydev** [smudge202/compose#81]
CommandLineApplication has a generic and also a default of an int (which seems superfluous but I can understand). The CancellableCommandLine then *forces* you into using an int, instead of simply using a generic and deferring the decision to the creator!

ServiceApplication might require some thinking also...

**Comment by smudge202** [comment]
Releates to #57

**Comment by herecydev** [comment]
Thoughts on the following ([for reference](https://github.com/smudge202/compose/blob/master/src/Compose/Executable.cs))?

# Abstract classes
Executable
Executable<TContext>
ReturningExecutable<TResult>
ReturningExecutable<TContext, TResult>

---

# Default implementations
CommandLineApplication<TResult> : ReturningExecutable<TResult>
CancellableCommandLineApplication<TResult> : ReturningExecutable<CancellationToken, TResult>
ServiceApplication : Executable<CancellationToken>

**Comment by smudge202** [comment]
```c#
CancellableCommandLineApplication<TResult> : ReturningExecutable<CancellationToken, TResult>
```

should just be

```c#
CommandLineApplication<TContext, TResult> : ReturningExecutable<TContext, TResult>
```

Was there a reason we did it differently?

**Comment by herecydev** [comment]
You left a junior alone!

**Comment by herecydev** [comment]
So...

## Default implementations
```c#
public class CommandLineApplication<TResult> : ReturningExecutable<TResult>
public class CommandLineApplication<TContext, TResult> : ReturningExecutable<TContext, TResult>
public class ServiceApplication : Executable<CancellationToken>
```

**Comment by smudge202** [comment]
No.

It's not wrong per se, simply most people are used to Command Line Applications being `void`. It's only because we follow the practice of returning Error codes that we find the `TResult` default as useful. The VS templates for Console apps on contrast default to `void`.

Debates over _correctness_ aside, we want to be easy to use for the majority.

As always, I've no suggestions on names.

**Comment by herecydev** [comment]
So a further `public class CommandLineApplication : Executable` would cater for those `void` applications.

**Comment by smudge202** [comment]
Almost. You'll need to split `CommandLineApplication` into two classes as you've suggested for `Executable`. So probably `CommandLineApplication` and `ReturnableCommandLineApplication`. Horrible name to expose but what can ya do.
