### ISSUE TITLE
Application IServiceCollection Intercepts

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#84]
One of our extensibility points is the ability to define new Application types ([Compose.Owin](https://github.com/smudge202/compose-owin) for example). Applications can override the `Execute` and `ExecuteAsync` virtual methods of `Executable`, but it feels like we're missing other points of interception.

For example, I typically use `TestApplication`s which allow me to perform _setup/teardown_ as part of the Execution. However, I'd also like the ability to examine and modify the `IServiceCollection`, potentially both before and after the host has completed `UseServices`.

Intercepting _before_ allows me to override services that would otherwise be `TryAdd`ed by the Host, whilst _after_ allows me to examine and modify the collection.

Thoughts?

**Comment by herecydev** [comment]
Very nice idea, shouldn't be breaking and allows for a nice level of extensibility and control over the application :shipit:

**Comment by smudge202** [comment]
Some possible implementation details to better clarify the proposal:

```c#
// change this method
public static void UseServices(this Application app, Action<IServiceCollection> configure)
{
  var services = new ServiceCollection();
  // the following method is virtual and just blank by default
  // the intent is to allow applications to define a service so
  // that implementations using `TryAdd` are skipped
  app.PreServiceConfiguration(services);
  // add host services:
  configure(services);
  // transitional stuff
  ApplyTransitions(services);
  // Again, a blank virtual method on Application
  // this time allowing visibility of the configured services
  // and the option to make changes to the service collection
  app.PostServiceConfiguration(services);
  // Compose then essentially persists the collection
  Persist(services);
}
```
