### ISSUE TITLE
Move to Test Attributes

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#85]
Make sure `test` command filters to unit tests, and second command for all.

**Comment by herecydev** [comment]
Got the fix, just struggling to build yours against dnxCore50. Have you got a different runtime to me? Building against beta4; only 4000 errors :S

**Comment by smudge202** [comment]
Was fine last time I played with it. Looks like we're wildcarding all the dependencies in the `project.json` so no surprise it breaks now. If you switch from nightly to release feed do you still get issues?

**Comment by herecydev** [comment]
Can't test now, will test on return. Wildcarding is too dangerous right now. IMO. I would raise an issue to lock down versions.

**Comment by smudge202** [comment]
Agreed, created #86 to address it.

**Comment by smudge202** [comment]
#86 was completed; think you'll be able to take another look, @herecydev ? Bear in mind #89, not sure if blocking?

**Comment by herecydev** [comment]
Resolved by #91
