### ISSUE TITLE
Dependency wild carding

### ISSUE THREAD

**Issue by smudge202** [smudge202/compose#86]
Although this may change in the future as we move onto stable builds and feeds, we need to switch from wildcards in the  `project.json`. This is causing problems on #85 .

**Comment by sblackler** [comment]
Will resolve as part of #72 

@herecydev do you want to do the test project while your doing 85? if not, let me know and will sort

**Comment by herecydev** [comment]
It's all ready to go, just need those versions anchored down. I will pull any commits down as and when they come in and PR changes up when it's all stable.

**Comment by sblackler** [comment]
Had to adjust the TFMs because `dotnet` isn't what we originally thought it was. See #87 for details

**Comment by sblackler** [comment]
In case you haven't already, you'll need to update to xunit beta3 as the test host changed its dependency from `DependencyInjection.Interfaces` to `DependencyInjection.Abstractions`. Just spent a good 20 mins trying to figure out why `ServiceDescriptor` was defined twice in my test project. Was using an outdated version of the dnx test runner which had a dependency on a beta4 test host, which used the interfaces package...

**Comment by smudge202** [comment]
Whenever confronted with issues like that, you can check the `project.lock.json` file to see the versions of libraries in use, and from what they are brought in by.
